package ar.edu.unlam.pb1.dominio;

public enum MenuPrincipal {
	// 1 2 3
	// 0 1 2
	AGREGAR_PLANTA, MODIFICAR_STOCK_PLANTA, BUSCAR_PLANTA_POR_CODIGO, BUSCAR_PLANTAS_QUE_CONTIENEN, VENDER_PLANTA,
	OBTENER_PLANTAS_DEL_TIPO, SALIR
}
